-- MySQL Script generated by MySQL Workbench
-- Sun 15 May 2022 09:26:30 PM BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shoppingList
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shoppingList` ;

-- -----------------------------------------------------
-- Schema shoppingList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingList` ;
USE `shoppingList` ;

-- -----------------------------------------------------
-- Table `shoppingList`.`groupTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingList`.`groupTable` ;

CREATE TABLE IF NOT EXISTS `shoppingList`.`groupTable` (
  `GroupName` VARCHAR(255) NOT NULL,
  `storageType` VARCHAR(45) NULL,
  `Red` INT(8) NULL,
  `Green` INT(8) NULL,
  `Blue` INT(8) NULL,
  PRIMARY KEY (`GroupName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingList`.`ItemTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingList`.`ItemTable` ;

CREATE TABLE IF NOT EXISTS `shoppingList`.`ItemTable` (
  `ItemName` VARCHAR(255) NOT NULL,
  `Price` DECIMAL NOT NULL,
  `GroupName` VARCHAR(45) NULL,
  PRIMARY KEY (`ItemName`),
  INDEX `GroupName_idx` (`GroupName` ASC) VISIBLE,
  CONSTRAINT `GroupName`
    FOREIGN KEY (`GroupName`)
    REFERENCES `shoppingList`.`groupTable` (`GroupName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `shoppingList`.`ListTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingList`.`ListTable` ;

CREATE TABLE IF NOT EXISTS `shoppingList`.`ListTable` (
  `ListName` VARCHAR(255) NOT NULL,
  `ListDescription` MEDIUMTEXT NULL,
  PRIMARY KEY (`ListName`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS APP;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'APP' IDENTIFIED BY '?QnH_cesvV*MH?9CGNG!FnHbW=unc&xZnq67*xPWYJLvsX5Z@a';

GRANT ALL ON `shoppingList`.* TO 'APP';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `shoppingList`.`ListLink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingList`.`ListLink` ;

CREATE TABLE IF NOT EXISTS `shoppingList`.`ListLink` (
  `ListName` VARCHAR(255) NOT NULL,
  `ItemName` VARCHAR(255) NOT NULL,
  `Quantity` INT NOT NULL DEFAULT 1,
  `Checked` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ListName`, `ItemName`),
  INDEX `ItemName_idx` (`ItemName` ASC) VISIBLE,
  CONSTRAINT `ListName`
    FOREIGN KEY (`ListName`)
    REFERENCES `shoppingList`.`ListTable` (`ListName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ItemName`
    FOREIGN KEY (`ItemName`)
    REFERENCES `shoppingList`.`ItemTable` (`ItemName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
